# -*- coding: utf-8 -*-

"""
/***************************************************************************
 processBaseLine
                                 A QGIS plugin
 Plugin que funciona como complemento al plugin Colector. Su función es procesar las líneas base de la información recolectada haciendo uso de RTKLIB tanto para convertir los archivos binarios creados a partir de la colección, como para realizar la corrección diferencial.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-18
        copyright            : (C) 2021 by Alexander Pretel Díaz
        email                : alexander.pretel@correounivalle.edu.co
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Alexander Pretel Díaz'
__date__ = '2021-04-18'
__copyright__ = '(C) 2021 by Alexander Pretel Díaz'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .process_provider import processBaseLineProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class processBaseLinePlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = processBaseLineProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
